### ISSUE TITLE
Support for `PyGC_Head`

### ISSUE THREAD

**Issue by ZeroIntensity** [ionite34/einspect#17]
before a `PyObject` is allocated, `PyGC_Head` comes right before (defined in [internal/pycore_gc.h](https://github.com/python/cpython/blob/main/Include/internal/pycore_gc.h)).

in c, its accessed like so:
```c
((PyGC_Head*)(my_object)-1);
```

would be interesting if einspect could support looking at these

**Comment by ionite34** [comment]
Should be doable yeah 👀
